# Generated by Django 3.1.7 on 2021-04-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='airdate',
            field=models.DateField(default='2021-04-04', verbose_name='Airdate'),
            preserve_default=False,
        ),
    ]
