# Generated by Django 3.1.6 on 2021-04-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_db', '0002_content_airdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformcontent',
            options={'verbose_name': 'Platform Content', 'verbose_name_plural': 'Platforms Contents'},
        ),
        migrations.AddField(
            model_name='statususercontent',
            name='date_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Date'),
        ),
    ]
