# Generated by Django 3.1.6 on 2021-04-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_db', '0003_auto_20210404_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('a', 'Movie'), ('b', 'Serie')], max_length=1, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='statususercontent',
            name='type',
            field=models.CharField(choices=[('a', 'Watching'), ('b', 'Watched'), ('c', 'Favourite'), ('d', 'Pending')], max_length=1, verbose_name='Status'),
        ),
    ]
