# Generated by Django 3.1.7 on 2021-05-10 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entertainment_db', '0004_auto_20210404_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)'),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('content', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='platformcontent',
            unique_together={('content', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='statususercontent',
            unique_together={('content', 'user')},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='value',
        ),
    ]
