# Generated by Django 3.1.7 on 2021-05-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_db', '0005_auto_20210510_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Serie')], max_length=6, verbose_name='Content Type'),
        ),
    ]
