# Generated by Django 3.1.7 on 2021-05-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_db', '0006_auto_20210512_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='poster_url',
            field=models.URLField(default=1, verbose_name='Poster'),
            preserve_default=False,
        ),
    ]
