# Generated by Django 3.1.7 on 2021-05-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_db', '0007_content_poster_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformcontent',
            name='id_in_platform',
        ),
    ]
